spring.application.name=notification-service
server.port=8085

spring.config.import=optional:configserver:http://localhost:9296

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379

#==========================================================
# Spring Boot Actuator
# ==========================================================

management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ==========================================================
# Micrometer Tracing
# ==========================================================

management.tracing.sampling.probability=1.0

# ==========================================================
# OpenTelemetry (OTLP -> Jaeger)
# ==========================================================

management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

management.tracing.enabled=true
management.observations.enabled=true

logging.pattern.level=%5p [traceId=%X{traceId} spanId=%X{spanId}]